fos_rest:
  param_fetcher_listener: true
  body_listener: true
  format_listener:
    enabled: true
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: 'json' }
  versioning: true
  view:
    view_response_listener: 'force'
