<?php

namespace ContainerKJzU0xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P4XXEEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P_4XXEE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P_4XXEE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ProductController::deleteProduct' => ['privates', '.service_locator.Rc9uH46', 'get_ServiceLocator_Rc9uH46Service', true],
            'App\\Controller\\ProductController::getProduct' => ['privates', '.service_locator.Rc9uH46', 'get_ServiceLocator_Rc9uH46Service', true],
            'App\\Controller\\ProductController::setViewHandler' => ['privates', '.service_locator.srPvxhL', 'get_ServiceLocator_SrPvxhLService', true],
            'App\\Controller\\ProductController::updateProduct' => ['privates', '.service_locator.Rc9uH46', 'get_ServiceLocator_Rc9uH46Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\ProductController:deleteProduct' => ['privates', '.service_locator.Rc9uH46', 'get_ServiceLocator_Rc9uH46Service', true],
            'App\\Controller\\ProductController:getProduct' => ['privates', '.service_locator.Rc9uH46', 'get_ServiceLocator_Rc9uH46Service', true],
            'App\\Controller\\ProductController:setViewHandler' => ['privates', '.service_locator.srPvxhL', 'get_ServiceLocator_SrPvxhLService', true],
            'App\\Controller\\ProductController:updateProduct' => ['privates', '.service_locator.Rc9uH46', 'get_ServiceLocator_Rc9uH46Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\ProductController::deleteProduct' => '?',
            'App\\Controller\\ProductController::getProduct' => '?',
            'App\\Controller\\ProductController::setViewHandler' => '?',
            'App\\Controller\\ProductController::updateProduct' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ProductController:deleteProduct' => '?',
            'App\\Controller\\ProductController:getProduct' => '?',
            'App\\Controller\\ProductController:setViewHandler' => '?',
            'App\\Controller\\ProductController:updateProduct' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
