<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAVcCLux\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAVcCLux/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAVcCLux.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAVcCLux\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAVcCLux\App_KernelDevDebugContainer([
    'container.build_hash' => 'AVcCLux',
    'container.build_id' => 'dd17e3c9',
    'container.build_time' => 1602852214,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAVcCLux');
